In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Carico il file Excel.
df_europa = pd.read_excel('DATI_EUROPEI_PERNOTTAMENTI.xlsx')
df_europa

,TIME,2019-01,Unnamed: 2,2019-02,Unnamed: 4,2019-03,Unnamed: 6,2019-04,Unnamed: 8,2019-05,...,2024-08,Unnamed: 136,2024-09,Unnamed: 138,2024-10,Unnamed: 140,2024-11,Unnamed: 142,2024-12,Unnamed: 144
0,GEO (Labels),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Germany,16860306.0,NaN,17904292.0,NaN,21959112.0,NaN,28101154.0,NaN,31630941.0,...,44114060.0,NaN,35423741.0,NaN,33426715.0,NaN,21754812.0,NaN,20596396.0,NaN
2,Spain,6644015.0,NaN,7734823.0,NaN,10467428.0,NaN,14047915.0,NaN,13045936.0,...,31672366.0,NaN,17587072.0,NaN,12705963.0,NaN,9766474.0,NaN,9736437.0,NaN
3,France,13542420.0,NaN,15910967.0,NaN,17194727.0,NaN,24297931.0,NaN,22866884.0,...,64853107.0,NaN,26644274.0,NaN,19099101.0,e,13901725.0,e,14698784.0,e
4,Italy,9736972.0,NaN,8997772.0,NaN,10756384.0,NaN,13114418.0,NaN,11940495.0,...,45922875.0,NaN,19088861.0,NaN,10028155.0,NaN,9592912.0,NaN,11179550.0,NaN

In [3]:
#Elimino le colonne che iniziano con 'Unnamed'
df_europa = df_europa.loc[:, ~df_europa.columns.str.contains('^Unnamed')]
df_europa.head()

,TIME,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,...,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
0,GEO (Labels),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Germany,16860306.0,17904292.0,21959112.0,28101154.0,31630941.0,37495716.0,42509653.0,42128643.0,34638616.0,...,25164346.0,25842165.0,36572597.0,35078335.0,41827077.0,44114060.0,35423741.0,33426715.0,21754812.0,20596396.0
2,Spain,6644015.0,7734823.0,10467428.0,14047915.0,13045936.0,17075122.0,24188680.0,31808954.0,16350901.0,...,13339144.0,12247435.0,15027647.0,19083134.0,25726563.0,31672366.0,17587072.0,12705963.0,9766474.0,9736437.0
3,France,13542420.0,15910967.0,17194727.0,24297931.0,22866884.0,29825030.0,51274577.0,64278610.0,26011951.0,...,17838726.0,22758487.0,28741270.0,28333591.0,49856971.0,64853107.0,26644274.0,19099101.0,13901725.0,14698784.0
4,Italy,9736972.0,8997772.0,10756384.0,13114418.0,11940495.0,24826346.0,37782553.0,50357143.0,19038104.0,...,10979743.0,11841632.0,12430919.0,24676433.0,36226091.0,45922875.0,19088861.0,10028155.0,9592912.0,11179550.0

In [4]:
#Elimino la riga 0 che contiene "GEO (Labels)" 
df_europa = df_europa[df_europa['TIME'] != 'GEO (Labels)']

#Faccio il MELT (Unpivot)
df_europa_long = df_europa.melt(id_vars=['TIME'], var_name='Data', value_name='Pernottamenti')
df_europa_long.head()

      TIME     Data  Pernottamenti
0  Germany  2019-01     16860306.0
1    Spain  2019-01      6644015.0
2   France  2019-01     13542420.0
3    Italy  2019-01      9736972.0
4  Germany  2019-02     17904292.0

In [5]:
#Rinomino la colonna da TIME a Paese
df_europa_long = df_europa_long.rename(columns={'TIME': 'Paese'})
df_europa_long.head()

     Paese     Data  Pernottamenti
0  Germany  2019-01     16860306.0
1    Spain  2019-01      6644015.0
2   France  2019-01     13542420.0
3    Italy  2019-01      9736972.0
4  Germany  2019-02     17904292.0

In [6]:
#Elimino eventuali spazi bianchi all'inizio o alla fine dei nomi.
df_europa_long['Paese'] = df_europa_long['Paese'].astype(str).str.strip()

In [7]:
#Creo il dizionario.
traduzione_paesi = {
    'Germany': 'Germania',
    'Spain': 'Spagna',
    'France': 'Francia',
    'Italy': 'Italia'
}

df_europa_long['Paese'] = df_europa_long['Paese'].map(traduzione_paesi)
df_europa_long.head()

      Paese     Data  Pernottamenti
0  Germania  2019-01     16860306.0
1    Spagna  2019-01      6644015.0
2   Francia  2019-01     13542420.0
3    Italia  2019-01      9736972.0
4  Germania  2019-02     17904292.0

In [8]:
#Trasformo pernottamenti in numeri interi.
df_europa_long['Pernottamenti'] = df_europa_long['Pernottamenti'].astype(int)
df_europa_long.head()

      Paese     Data  Pernottamenti
0  Germania  2019-01       16860306
1    Spagna  2019-01        6644015
2   Francia  2019-01       13542420
3    Italia  2019-01        9736972
4  Germania  2019-02       17904292

In [9]:
df_europa_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288 entries, 0 to 287
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Paese          288 non-null    object
 1   Data           288 non-null    object
 2   Pernottamenti  288 non-null    int32
dtypes: int32(1), object(2)
memory usage: 5.8+ KB

In [10]:
#Trasformo la colonna Data da testo a "Vera Data". 
df_europa_long['Data'] = pd.to_datetime(df_europa_long['Data'])
df_europa_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288 entries, 0 to 287
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Paese          288 non-null    object
 1   Data           288 non-null    datetime64[ns]
 2   Pernottamenti  288 non-null    int32
dtypes: datetime64[ns](1), int32(1), object(1)
memory usage: 5.8+ KB

In [11]:
print(df_europa_long.isnull().sum())

Paese            0
Data             0
Pernottamenti    0
dtype: int64

In [12]:
df_europa_long.describe()

                      Data  Pernottamenti
count                  288   2.880000e+02
mean   2021-12-15 22:40:00   1.986821e+07
min    2019-01-01 00:00:00   0.000000e+00
25%    2020-06-23 12:00:00   9.711555e+06
50%    2021-12-16 12:00:00   1.629564e+07
75%    2023-06-08 12:00:00   2.707616e+07
max    2024-12-01 00:00:00   6.789428e+07
std                    NaN   1.400305e+07

In [13]:
#Salvo
df_europa_long.to_excel('DATI_EUROPA_PULITi.xlsx', index=False)