In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Mi carico il file Excel.
df = pd.read_excel('PERNOTTAMENTI_ITALIA_REGIONI_2019_2024.xlsx')
df

,TIME,2019,Unnamed: 2,2020,Unnamed: 4,2021,Unnamed: 6,2022,Unnamed: 8,2023,Unnamed: 10,2024
0,GEO (Labels),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Piemonte,8351424.0,NaN,4372061.0,NaN,5782004.0,NaN,7270164.0,NaN,7229845.0,NaN,7033710.0
2,Valle d’Aosta/Vallée d’Aoste,2113001.0,NaN,1452461.0,NaN,1479842.0,NaN,2109248.0,NaN,2253209.0,NaN,2163362.0
3,Liguria,8932884.0,NaN,6493583.0,NaN,7933782.0,NaN,8888698.0,NaN,8845282.0,NaN,8734589.0
4,Lombardia,16229378.0,NaN,8790626.0,NaN,13093377.0,NaN,16028865.0,NaN,15494685.0,NaN,15880818.0
5,Abruzzo,5383234.0,NaN,3779939.0,NaN,4726288.0,NaN,5419540.0,NaN,5825896.0,NaN,6092117.0
6,Molise,404901.0,NaN,317759.0,NaN,431573.0,NaN,376660.0,NaN,447289.0,NaN,413949.0
7,Campania,11383367.0,NaN,5973068.0,NaN,7965805.0,NaN,9312047.0,NaN,10093962.0,NaN,9727103.0
8,Puglia,11598644.0,NaN,8940988.0,NaN,11577558.0,NaN,11738303.0,NaN,11714009.0,NaN,11862805.0
9,Basilicata,2392796.0,NaN,1308083.0,NaN,1669567.0,NaN,1900322.0,NaN,2109144.0,NaN,2063447.0
10,Calabria,7315264.0,NaN,4210219.0,NaN,5348243.0,NaN,6065688.0,NaN,6614203.0,NaN,6537862.0
11,Sicilia,7483403.0,NaN,5165065.0,NaN,6982941.0,NaN,8355072.0,NaN,8427343.0,NaN,8650869.0
12,Sardegna,7418767.0,NaN,4739031.0,NaN,6869523.0,NaN,7994435.0,NaN,7382591.0,NaN,7633588.0
13,Provincia Autonoma di Bolzano/Bozen,10198947.0,NaN,8855000.0,NaN,9001916.0,NaN,10823496.0,NaN,10649009.0,NaN,10494103.0
14,Provincia Autonoma di Trento,10743000.0,NaN,7973937.0,NaN,8208278.0,NaN,10775002.0,NaN,11033318.0,NaN,11025390.0
15,Veneto,23068000.0,NaN,17230354.0,NaN,22344562.0,NaN,21868391.0,NaN,22097826.0,NaN,21693890.0
16,Friuli-Venezia Giulia,3898039.0,NaN,2896065.0,NaN,3758713.0,NaN,4110859.0,NaN,4149828.0,NaN,4131497.0
17,Emilia-Romagna,29748437.0,NaN,19028583.0,NaN,25299960.0,NaN,28380339.0,NaN,28088683.0,NaN,28567193.0
18,Toscana,22317283.0,NaN,15916940.0,NaN,19963549.0,NaN,20963298.0,NaN,20722001.0,NaN,19599594.0
19,Umbria,3810497.0,NaN,2546477.0,NaN,3485343.0,NaN,4023867.0,NaN,4261852.0,NaN,4366760.0
20,Marche,8647855.0,NaN,6934627.0,NaN,8592636.0,NaN,9043229.0,NaN,8931093.0,NaN,8572481.0
21,Lazio,14637466.0,NaN,6078612.0,NaN,8539507.0,NaN,15491575.0,NaN,16616726.0,NaN,16964475.0

In [3]:
#Uso .shape per vedere quante colonne e righe ci sono.
df.shape

(22, 12)

In [4]:
#Uso .info per vedere le informazioni generali del dataset con relativo tipo di dato.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TIME         22 non-null     object
 1   2019         21 non-null     float64
 2   Unnamed: 2   0 non-null      float64
 3   2020         21 non-null     float64
 4   Unnamed: 4   0 non-null      float64
 5   2021         21 non-null     float64
 6   Unnamed: 6   0 non-null      float64
 7   2022         21 non-null     float64
 8   Unnamed: 8   0 non-null      float64
 9   2023         21 non-null     float64
 10  Unnamed: 10  0 non-null      float64
 11  2024         21 non-null     float64
dtypes: float64(11), object(1)
memory usage: 2.2+ KB

In [5]:
#Mi tengo solo le colonne che mi servono e non vuote.
df = df.loc[:, ~df.columns.str.contains('^Unnamed')] 
#Controllo che non ci siano le colonne vuote.
df.head()

,TIME,2019,2020,2021,2022,2023,2024
0,GEO (Labels),NaN,NaN,NaN,NaN,NaN,NaN
1,Piemonte,8351424.0,4372061.0,5782004.0,7270164.0,7229845.0,7033710.0
2,Valle d’Aosta/Vallée d’Aoste,2113001.0,1452461.0,1479842.0,2109248.0,2253209.0,2163362.0
3,Liguria,8932884.0,6493583.0,7933782.0,8888698.0,8845282.0,8734589.0
4,Lombardia,16229378.0,8790626.0,13093377.0,16028865.0,15494685.0,15880818.0

In [6]:
#Elimino la riga 0 che contiene "GEO (Labels)"
df = df[df['TIME'] != 'GEO (Labels)']

#Faccio il MELT ovvero (l'Unpivot) trasformando la tabella da orizzontale a verticale.
df_long = df.melt(id_vars=['TIME'], var_name='Anno', value_name='Pernottamenti')

#Controllo il risultato finale.
df_long.head(15)

                                   TIME  Anno  Pernottamenti
0                              Piemonte  2019      8351424.0
1          Valle d’Aosta/Vallée d’Aoste  2019      2113001.0
2                               Liguria  2019      8932884.0
3                             Lombardia  2019     16229378.0
4                               Abruzzo  2019      5383234.0
5                                Molise  2019       404901.0
6                              Campania  2019     11383367.0
7                                Puglia  2019     11598644.0
8                            Basilicata  2019      2392796.0
9                              Calabria  2019      7315264.0
10                              Sicilia  2019      7483403.0
11                             Sardegna  2019      7418767.0
12  Provincia Autonoma di Bolzano/Bozen  2019     10198947.0
13         Provincia Autonoma di Trento  2019     10743000.0
14                               Veneto  2019     23068000.0

In [7]:
#Controllo anche le ultime righe.
df_long.tail(5)

               TIME  Anno  Pernottamenti
121  Emilia-Romagna  2024     28567193.0
122         Toscana  2024     19599594.0
123          Umbria  2024      4366760.0
124          Marche  2024      8572481.0
125           Lazio  2024     16964475.0

In [8]:
#Ricontrollo quante righe e colonne.
df_long.shape

(126, 3)

In [9]:
#Rinomino la colonna TIME in Regione.
df_long = df_long.rename(columns={'TIME': 'Regione'})

#Visualizzo le prime righe per vedere se il nome è cambiato.
df_long.head()

                        Regione  Anno  Pernottamenti
0                      Piemonte  2019      8351424.0
1  Valle d’Aosta/Vallée d’Aoste  2019      2113001.0
2                       Liguria  2019      8932884.0
3                     Lombardia  2019     16229378.0
4                       Abruzzo  2019      5383234.0

In [10]:
#Tolgo gli spazi vuoti all'inizio e alla fine dei nomi delle regioni.
df_long['Regione'] = df_long['Regione'].str.strip()

#Controllo i nomi unici delle regioni.
df_long['Regione'].unique()

array(['Piemonte', 'Valle d’Aosta/Vallée d’Aoste', 'Liguria', 'Lombardia',
       'Abruzzo', 'Molise', 'Campania', 'Puglia', 'Basilicata',
       'Calabria', 'Sicilia', 'Sardegna',
       'Provincia Autonoma di Bolzano/Bozen',
       'Provincia Autonoma di Trento', 'Veneto', 'Friuli-Venezia Giulia',
       'Emilia-Romagna', 'Toscana', 'Umbria', 'Marche', 'Lazio'],
      dtype=object)

In [11]:
#Sostituisco i nomi delle regioni.
df_long['Regione'] = df_long['Regione'].replace({
    'Valle d’Aosta/Vallée d’Aoste': "Valle d'Aosta",
    'Provincia Autonoma di Bolzano/Bozen': 'Trentino-Alto Adige',
    'Provincia Autonoma di Trento': 'Trentino-Alto Adige'
})

#Controllo che siano stati cambiati. 
df_long['Regione'].unique()

array(['Piemonte', "Valle d'Aosta", 'Liguria', 'Lombardia', 'Abruzzo',
       'Molise', 'Campania', 'Puglia', 'Basilicata', 'Calabria',
       'Sicilia', 'Sardegna', 'Trentino-Alto Adige', 'Veneto',
       'Friuli-Venezia Giulia', 'Emilia-Romagna', 'Toscana', 'Umbria',
       'Marche', 'Lazio'], dtype=object)

In [12]:
#Sommo i valori di Bolzano e Trento.
df_long = df_long.groupby(['Regione', 'Anno'], as_index=False)['Pernottamenti'].sum()

#Ordino per Regione e per Anno.
df_long = df_long.sort_values(by=['Regione', 'Anno'])

In [13]:
#Ricontrollo che le righe siano diminuite.
df_long.shape

(120, 3)

In [14]:
#Trasformo i Pernottamenti in numeri interi (senza il .0).
df_long['Pernottamenti'] = df_long['Pernottamenti'].astype(int)

#Controllo il risultato.
df_long.head()

   Regione  Anno  Pernottamenti
0  Abruzzo  2019        5383234
1  Abruzzo  2020        3779939
2  Abruzzo  2021        4726288
3  Abruzzo  2022        5419540
4  Abruzzo  2023        5825896

In [15]:
#Controllo che la colonna Pernottamenti abbia il tipo di dato diverso ovvero da float a int.
df_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Regione        120 non-null    object
 1   Anno           120 non-null    object
 2   Pernottamenti  120 non-null    int32
dtypes: int32(1), object(2)
memory usage: 2.5+ KB

In [28]:
#Salvo
df_long.to_excel('PERNOTTAMENTI_REGIONI_ITALIA_2019_2024_PULITO.xlsx', index=False)